package workspace

import (
	"bufio"
	"context"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/tinywideclouds.com/thinkspace/internal/chat"
)

// Service orchestrates the workspace lifecycle using the ChatEngine.
type Service struct {
	logger        *slog.Logger
	engine        ChatEngine
	workspaceRoot string
	bus           *chat.EventBus
}

func NewService(logger *slog.Logger, engine ChatEngine, workspaceRoot string, bus *chat.EventBus) *Service {
	return &Service{
		logger:        logger,
		engine:        engine,
		workspaceRoot: workspaceRoot,
		bus:           bus,
	}
}

func (s *Service) PreviewCandidate(ctx context.Context, thread *chat.Thread, candidateID string) error {
	return s.engine.PreviewCandidate(ctx, thread.ID, candidateID)
}

func (s *Service) ResolveCandidate(ctx context.Context, thread *chat.Thread, candidateID string, accept bool, reason string) error {
	if accept {
		if err := s.engine.Accept(ctx, thread.ID, candidateID, reason); err != nil {
			return fmt.Errorf("accepting candidate: %w", err)
		}
	} else {
		if err := s.engine.Reject(ctx, thread.ID, candidateID, reason); err != nil {
			return fmt.Errorf("rejecting candidate: %w", err)
		}
	}

	if err := s.LogResolution(ctx, thread, candidateID, accept, reason); err != nil {
		s.logger.ErrorContext(ctx, "failed to log resolution to ledger", "error", err)
	}

	return nil
}

func (s *Service) StartThread(ctx context.Context, id string) (*chat.Thread, error) {
	threadDir := filepath.Join(s.workspaceRoot, "chats", id)
	ledgerPath := filepath.Join(threadDir, "conversation.jsonl")

	s.logger.InfoContext(ctx, "starting thread", slog.String("id", id))

	if err := s.engine.InitChat(ctx, id); err != nil {
		return nil, fmt.Errorf("initializing chat state: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(threadDir, "docs"), 0755); err != nil {
		return nil, fmt.Errorf("creating thread directories: %w", err)
	}

	f, err := os.OpenFile(ledgerPath, os.O_CREATE|os.O_RDWR, 0644)
	if err == nil {
		f.Close()
	}

	return &chat.Thread{
		ID:         id,
		SpaceID:    filepath.Base(s.workspaceRoot),
		Branch:     "chat/" + id,
		LedgerPath: ledgerPath,
		Dir:        threadDir,
	}, nil
}

func (s *Service) ProposeCandidate(ctx context.Context, thread *chat.Thread, toolName string, files map[string][]byte) (*Candidate, error) {
	now := time.Now().UTC()
	candidateID := fmt.Sprintf("%s-%d", toolName, now.Unix())

	s.logger.InfoContext(ctx, "proposing candidate", slog.String("candidate_id", candidateID))

	sandbox, err := s.engine.SpawnCandidateSandbox(ctx, thread.ID, candidateID)
	if err != nil {
		return nil, fmt.Errorf("spawning sandbox: %w", err)
	}
	defer sandbox.TearDown(ctx)

	var fileList []string
	for relativePath, content := range files {
		cleanPath := filepath.Clean(relativePath)
		if err := sandbox.WriteFile(ctx, filepath.Join("chats", thread.ID, "docs", cleanPath), content); err != nil {
			return nil, fmt.Errorf("writing file %s to sandbox: %w", cleanPath, err)
		}
		fileList = append(fileList, cleanPath)
	}

	commitMessage := fmt.Sprintf("auto(candidate): generated by %s", toolName)
	if err := sandbox.ApplyDraft(ctx, commitMessage); err != nil {
		return nil, fmt.Errorf("applying sandbox draft: %w", err)
	}

	if err := sandbox.DeliverForReview(ctx); err != nil {
		return nil, fmt.Errorf("delivering sandbox for review: %w", err)
	}

	if err := s.engine.PreviewCandidate(ctx, thread.ID, candidateID); err != nil {
		return nil, fmt.Errorf("previewing candidate: %w", err)
	}

	description := fmt.Sprintf("Proposed files: %s", strings.Join(fileList, ", "))
	if err := s.LogProposal(ctx, thread, candidateID, description, nil); err != nil {
		s.logger.ErrorContext(ctx, "failed to log proposal", "error", err)
	}

	return &Candidate{
		ID:        candidateID,
		ThreadID:  thread.ID,
		Branch:    "candidate/" + candidateID,
		CommitSHA: "head",
		Status:    StatusPending,
		CreatedAt: now,
	}, nil
}

func (s *Service) Checkpoint(ctx context.Context, thread *chat.Thread, reason string) (string, error) {
	s.logger.DebugContext(ctx, "checkpointing thread state", slog.String("thread_id", thread.ID))

	msg := fmt.Sprintf("chore(ledger): %s", reason)
	sha, err := s.engine.Snapshot(ctx, thread.ID, msg)
	if err != nil {
		return "", fmt.Errorf("snapshotting checkpoint: %w", err)
	}

	return sha, nil
}

func (s *Service) LoadEvents(ctx context.Context, thread *chat.Thread) ([]chat.Event, error) {
	var events []chat.Event

	file, err := os.Open(thread.LedgerPath)
	if err != nil {
		return nil, fmt.Errorf("opening ledger: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Bytes()
		if len(line) == 0 {
			continue
		}

		var ev chat.Event
		if err := json.Unmarshal(line, &ev); err != nil {
			s.logger.WarnContext(ctx, "skipping malformed ledger entry", slog.String("error", err.Error()))
			continue
		}
		events = append(events, ev)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scanning ledger: %w", err)
	}

	return events, nil
}

func (s *Service) LogUserPrompt(ctx context.Context, thread *chat.Thread, content string) error {
	event := chat.NewEvent(chat.EventPrompt, content)
	return s.bus.Publish(ctx, thread, event)
}

func (s *Service) LogUserMessage(ctx context.Context, thread *chat.Thread, content string) error {
	event := chat.NewEvent(chat.EventPrompt, content)
	return s.bus.Publish(ctx, thread, event)
}

func (s *Service) LogModelResponse(ctx context.Context, thread *chat.Thread, content string) error {
	event := chat.NewEvent(chat.EventModel, content)
	return s.bus.Publish(ctx, thread, event)
}

func (s *Service) LogProposal(ctx context.Context, thread *chat.Thread, candidateID string, description string, tags []string) error {
	event := chat.NewEvent(chat.EventCandidate, description)
	event.Tags = tags
	event.Metadata = map[string]string{
		"proposal_uid": candidateID,
	}
	return s.bus.Publish(ctx, thread, event)
}

func (s *Service) LogResolution(ctx context.Context, thread *chat.Thread, candidateID string, accepted bool, reason string) error {
	status := "REJECTED"
	if accepted {
		status = "ACCEPTED"
	}
	event := chat.NewEvent(chat.EventResolution, fmt.Sprintf("Proposal %s %s. Reason: %s", candidateID, status, reason))
	event.Metadata = map[string]string{
		"proposal_uid": candidateID,
		"status":       status,
		"reason":       reason,
	}
	return s.bus.Publish(ctx, thread, event)
}

func (s *Service) ReadCandidate(ctx context.Context, thread *chat.Thread, candidateID string) (string, error) {
	s.logger.DebugContext(ctx, "reading candidate contents", slog.String("candidate_id", candidateID))

	diff, err := s.engine.ReadCandidateDiff(ctx, thread.ID, candidateID)
	if err != nil {
		return "", fmt.Errorf("reading candidate diff: %w", err)
	}

	return diff, nil
}

func (s *Service) SpawnSandbox(ctx context.Context, threadID, candidateID string) (CandidateSandbox, error) {
	return s.engine.SpawnCandidateSandbox(ctx, threadID, candidateID)
}

func (s *Service) WorkspaceRoot() string {
	return s.workspaceRoot
}

func (s *Service) SaveReceipt(ctx context.Context, thread *chat.Thread, receipt FlowReceipt) error {
	receiptDir := filepath.Join(thread.Dir, "receipts")
	if err := os.MkdirAll(receiptDir, 0755); err != nil {
		return fmt.Errorf("creating receipts directory: %w", err)
	}

	b, err := xml.MarshalIndent(receipt, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling receipt: %w", err)
	}

	path := filepath.Join(receiptDir, fmt.Sprintf("%s.xml", receipt.FlowID))
	return os.WriteFile(path, append([]byte(xml.Header), b...), 0644)
}

func (s *Service) GetReceipt(ctx context.Context, thread *chat.Thread, flowID string) ([]byte, error) {
	path := filepath.Join(thread.Dir, "receipts", fmt.Sprintf("%s.xml", flowID))
	return os.ReadFile(path)
}
