package workspace

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Service orchestrates the workspace lifecycle using the ChatEngine.
type Service struct {
	logger        *slog.Logger
	engine        ChatEngine
	workspaceRoot string
}

func NewService(logger *slog.Logger, engine ChatEngine, workspaceRoot string) *Service {
	return &Service{
		logger:        logger,
		engine:        engine,
		workspaceRoot: workspaceRoot,
	}
}

// PreviewCandidate exposes the state engine's preview functionality to the orchestrator.
func (s *Service) PreviewCandidate(ctx context.Context, thread *Thread, candidateID string) error {
	return s.engine.PreviewCandidate(ctx, thread.ID, candidateID)
}

// ResolveCandidate processes the human decision and explicitly records the reason.
func (s *Service) ResolveCandidate(ctx context.Context, thread *Thread, candidateID string, accept bool, reason string) error {
	if accept {
		if err := s.engine.Accept(ctx, thread.ID, candidateID, reason); err != nil {
			return fmt.Errorf("accepting candidate: %w", err)
		}
	} else {
		if err := s.engine.Reject(ctx, thread.ID, candidateID, reason); err != nil {
			return fmt.Errorf("rejecting candidate: %w", err)
		}
	}

	if err := s.LogResolution(ctx, thread, candidateID, accept, reason); err != nil {
		s.logger.ErrorContext(ctx, "failed to log resolution to ledger", "error", err)
	}

	return nil
}

// StartThread initializes a new logical workspace and establishes its state.
func (s *Service) StartThread(ctx context.Context, id string) (*Thread, error) {
	threadDir := filepath.Join(s.workspaceRoot, "chats", id)
	ledgerPath := filepath.Join(threadDir, "conversation.jsonl")

	s.logger.InfoContext(ctx, "starting thread", slog.String("id", id))

	if err := s.engine.InitChat(ctx, id); err != nil {
		return nil, fmt.Errorf("initializing chat state: %w", err)
	}

	if err := os.MkdirAll(filepath.Join(threadDir, "docs"), 0755); err != nil {
		return nil, fmt.Errorf("creating thread directories: %w", err)
	}

	f, err := os.OpenFile(ledgerPath, os.O_CREATE|os.O_RDWR, 0644)
	if err == nil {
		f.Close()
	}

	return &Thread{
		ID:         id,
		Branch:     "chat/" + id,
		LedgerPath: ledgerPath,
		Dir:        threadDir,
	}, nil
}

// ProposeCandidate simulates a full agentic loop for a static payload.
func (s *Service) ProposeCandidate(ctx context.Context, thread *Thread, toolName string, files map[string][]byte) (*Candidate, error) {
	now := time.Now().UTC()
	candidateID := fmt.Sprintf("%s-%d", toolName, now.Unix())

	s.logger.InfoContext(ctx, "proposing candidate", slog.String("candidate_id", candidateID))

	// 1. Spawn isolated environment
	sandbox, err := s.engine.SpawnCandidateSandbox(ctx, thread.ID, candidateID)
	if err != nil {
		return nil, fmt.Errorf("spawning sandbox: %w", err)
	}

	// Ensure cleanup of the physical sandbox even if subsequent steps fail
	defer sandbox.TearDown(ctx)

	var fileList []string

	// 2. Write tool outputs into the isolated virtual sandbox
	for relativePath, content := range files {
		cleanPath := filepath.Clean(relativePath)
		if err := sandbox.WriteFile(ctx, filepath.Join("chats", thread.ID, "docs", cleanPath), content); err != nil {
			return nil, fmt.Errorf("writing file %s to sandbox: %w", cleanPath, err)
		}
		fileList = append(fileList, cleanPath)
	}

	// 3. Apply the draft to the sandbox
	commitMessage := fmt.Sprintf("auto(candidate): generated by %s", toolName)
	if err := sandbox.ApplyDraft(ctx, commitMessage); err != nil {
		return nil, fmt.Errorf("applying sandbox draft: %w", err)
	}

	// 4. Deliver back to main thread context
	if err := sandbox.DeliverForReview(ctx); err != nil {
		return nil, fmt.Errorf("delivering sandbox for review: %w", err)
	}

	// 5. Preview the candidate locally for the user
	if err := s.engine.PreviewCandidate(ctx, thread.ID, candidateID); err != nil {
		return nil, fmt.Errorf("previewing candidate: %w", err)
	}

	// 6. Log resolution to ledger
	if err := s.LogProposal(ctx, thread, candidateID, fileList); err != nil {
		s.logger.ErrorContext(ctx, "failed to log proposal", "error", err)
	}

	return &Candidate{
		ID:        candidateID,
		ThreadID:  thread.ID,
		Branch:    "candidate/" + candidateID,
		CommitSHA: "head",
		Status:    StatusPending,
		CreatedAt: now,
	}, nil
}

// AppendEvent writes an interaction to the append-only ledger on disk.
func (s *Service) AppendEvent(ctx context.Context, thread *Thread, ev Event) error {
	b, err := json.Marshal(ev)
	if err != nil {
		return fmt.Errorf("marshaling event: %w", err)
	}

	f, err := os.OpenFile(thread.LedgerPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return fmt.Errorf("opening ledger: %w", err)
	}
	defer f.Close()

	if _, err := f.Write(append(b, '\n')); err != nil {
		return fmt.Errorf("writing event: %w", err)
	}

	return nil
}

// Checkpoint safely commits the current state of the Thread branch.
func (s *Service) Checkpoint(ctx context.Context, thread *Thread, reason string) (string, error) {
	s.logger.DebugContext(ctx, "checkpointing thread state", slog.String("thread_id", thread.ID))

	msg := fmt.Sprintf("chore(ledger): %s", reason)
	sha, err := s.engine.Snapshot(ctx, thread.ID, msg)
	if err != nil {
		return "", fmt.Errorf("snapshotting checkpoint: %w", err)
	}

	return sha, nil
}

// LoadEvents parses the append-only ledger and returns the full event history.
func (s *Service) LoadEvents(ctx context.Context, thread *Thread) ([]Event, error) {
	var events []Event

	file, err := os.Open(thread.LedgerPath)
	if err != nil {
		return nil, fmt.Errorf("opening ledger: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Bytes()
		if len(line) == 0 {
			continue
		}

		var ev Event
		if err := json.Unmarshal(line, &ev); err != nil {
			s.logger.WarnContext(ctx, "skipping malformed ledger entry", slog.String("error", err.Error()))
			continue
		}
		events = append(events, ev)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scanning ledger: %w", err)
	}

	return events, nil
}

// LogUserPrompt creates and appends a user prompt event to the ledger.
func (s *Service) LogUserPrompt(ctx context.Context, thread *Thread, content string) error {
	ev := Event{
		ID:        fmt.Sprintf("usr-%d", time.Now().UnixNano()),
		Timestamp: time.Now().UTC(),
		Type:      EventPrompt,
		Content:   content,
	}
	return s.AppendEvent(ctx, thread, ev)
}

// LogUserMessage explicitly records an injected system or evaluation prompt into the ledger.
func (s *Service) LogUserMessage(ctx context.Context, thread *Thread, content string) error {
	ev := Event{
		ID:        fmt.Sprintf("usr-%d", time.Now().UnixNano()),
		Timestamp: time.Now().UTC(),
		Type:      EventPrompt,
		Content:   content,
	}
	return s.AppendEvent(ctx, thread, ev)
}

// LogModelResponse creates and appends a model output event to the ledger.
func (s *Service) LogModelResponse(ctx context.Context, thread *Thread, content string) error {
	ev := Event{
		ID:        fmt.Sprintf("mdl-%d", time.Now().UnixNano()),
		Timestamp: time.Now().UTC(),
		Type:      EventModel,
		Content:   content,
	}
	return s.AppendEvent(ctx, thread, ev)
}

// LogProposal records the generation of a candidate.
func (s *Service) LogProposal(ctx context.Context, thread *Thread, candidateID string, files []string) error {
	ev := Event{
		ID:        fmt.Sprintf("evt-%d", time.Now().UnixNano()),
		Timestamp: time.Now().UTC(),
		Type:      EventCandidate,
		Content:   fmt.Sprintf("Proposed files: %s", strings.Join(files, ", ")),
		Metadata: map[string]string{
			"proposal_uid": candidateID,
			"files":        strings.Join(files, ","),
		},
	}
	return s.AppendEvent(ctx, thread, ev)
}

// LogResolution records the outcome of a candidate.
func (s *Service) LogResolution(ctx context.Context, thread *Thread, candidateID string, accepted bool, reason string) error {
	status := "REJECTED"
	if accepted {
		status = "ACCEPTED"
	}
	ev := Event{
		ID:        fmt.Sprintf("evt-%d", time.Now().UnixNano()),
		Timestamp: time.Now().UTC(),
		Type:      EventResolution,
		Content:   fmt.Sprintf("Proposal %s %s. Reason: %s", candidateID, status, reason),
		Metadata: map[string]string{
			"proposal_uid": candidateID,
			"status":       status,
			"reason":       reason,
		},
	}
	return s.AppendEvent(ctx, thread, ev)
}

// ReadCandidate fetches the changes made in a specific candidate branch
// so the Manager LLM can review the sub-agent's work.
func (s *Service) ReadCandidate(ctx context.Context, thread *Thread, candidateID string) (string, error) {
	s.logger.DebugContext(ctx, "reading candidate contents", slog.String("candidate_id", candidateID))

	diff, err := s.engine.ReadCandidateDiff(ctx, thread.ID, candidateID)
	if err != nil {
		return "", fmt.Errorf("reading candidate diff: %w", err)
	}

	return diff, nil
}

// SpawnSandbox encapsulates creating an isolated agent sandbox environment.
func (s *Service) SpawnSandbox(ctx context.Context, threadID, candidateID string) (CandidateSandbox, error) {
	return s.engine.SpawnCandidateSandbox(ctx, threadID, candidateID)
}

// WorkspaceRoot returns the base path for relative path calculations.
func (s *Service) WorkspaceRoot() string {
	return s.workspaceRoot
}
