// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: src/thinkspace/api/v1/events.proto

package api_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Enums ---
type DelegationStrategy int32

const (
	DelegationStrategy_DELEGATION_STRATEGY_UNSPECIFIED DelegationStrategy = 0
	DelegationStrategy_DELEGATION_STRATEGY_SKIP        DelegationStrategy = 1
	DelegationStrategy_DELEGATION_STRATEGY_MANUAL      DelegationStrategy = 2
	DelegationStrategy_DELEGATION_STRATEGY_REVIEW      DelegationStrategy = 3
	DelegationStrategy_DELEGATION_STRATEGY_REFINE      DelegationStrategy = 4
)

// Enum value maps for DelegationStrategy.
var (
	DelegationStrategy_name = map[int32]string{
		0: "DELEGATION_STRATEGY_UNSPECIFIED",
		1: "DELEGATION_STRATEGY_SKIP",
		2: "DELEGATION_STRATEGY_MANUAL",
		3: "DELEGATION_STRATEGY_REVIEW",
		4: "DELEGATION_STRATEGY_REFINE",
	}
	DelegationStrategy_value = map[string]int32{
		"DELEGATION_STRATEGY_UNSPECIFIED": 0,
		"DELEGATION_STRATEGY_SKIP":        1,
		"DELEGATION_STRATEGY_MANUAL":      2,
		"DELEGATION_STRATEGY_REVIEW":      3,
		"DELEGATION_STRATEGY_REFINE":      4,
	}
)

func (x DelegationStrategy) Enum() *DelegationStrategy {
	p := new(DelegationStrategy)
	*p = x
	return p
}

func (x DelegationStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DelegationStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_src_thinkspace_api_v1_events_proto_enumTypes[0].Descriptor()
}

func (DelegationStrategy) Type() protoreflect.EnumType {
	return &file_src_thinkspace_api_v1_events_proto_enumTypes[0]
}

func (x DelegationStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DelegationStrategy.Descriptor instead.
func (DelegationStrategy) EnumDescriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{0}
}

// --- Shared Types ---
type SpaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceInfo) Reset() {
	*x = SpaceInfo{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceInfo) ProtoMessage() {}

func (x *SpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceInfo.ProtoReflect.Descriptor instead.
func (*SpaceInfo) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *SpaceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// --- Outbound Payloads (Server -> Client) ---
type ChatStreamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamPayload) Reset() {
	*x = ChatStreamPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamPayload) ProtoMessage() {}

func (x *ChatStreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamPayload.ProtoReflect.Descriptor instead.
func (*ChatStreamPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ChatStreamPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LogMessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessagePayload) Reset() {
	*x = LogMessagePayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessagePayload) ProtoMessage() {}

func (x *LogMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessagePayload.ProtoReflect.Descriptor instead.
func (*LogMessagePayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *LogMessagePayload) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogMessagePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelegationStartPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCount    int32                  `protobuf:"varint,1,opt,name=agent_count,json=agentCount,proto3" json:"agent_count,omitempty"`
	Instructions  string                 `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationStartPayload) Reset() {
	*x = DelegationStartPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationStartPayload) ProtoMessage() {}

func (x *DelegationStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationStartPayload.ProtoReflect.Descriptor instead.
func (*DelegationStartPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *DelegationStartPayload) GetAgentCount() int32 {
	if x != nil {
		return x.AgentCount
	}
	return 0
}

func (x *DelegationStartPayload) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type DelegationCompletePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationCompletePayload) Reset() {
	*x = DelegationCompletePayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationCompletePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationCompletePayload) ProtoMessage() {}

func (x *DelegationCompletePayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationCompletePayload.ProtoReflect.Descriptor instead.
func (*DelegationCompletePayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *DelegationCompletePayload) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type AgentStartPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int32                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Instructions  string                 `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStartPayload) Reset() {
	*x = AgentStartPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStartPayload) ProtoMessage() {}

func (x *AgentStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStartPayload.ProtoReflect.Descriptor instead.
func (*AgentStartPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *AgentStartPayload) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentStartPayload) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type AgentStreamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int32                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamPayload) Reset() {
	*x = AgentStreamPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamPayload) ProtoMessage() {}

func (x *AgentStreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamPayload.ProtoReflect.Descriptor instead.
func (*AgentStreamPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *AgentStreamPayload) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentStreamPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AgentCompletePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int32                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Verified      bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCompletePayload) Reset() {
	*x = AgentCompletePayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCompletePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCompletePayload) ProtoMessage() {}

func (x *AgentCompletePayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCompletePayload.ProtoReflect.Descriptor instead.
func (*AgentCompletePayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *AgentCompletePayload) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentCompletePayload) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *AgentCompletePayload) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type RequestStrategyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStrategyPayload) Reset() {
	*x = RequestStrategyPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStrategyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStrategyPayload) ProtoMessage() {}

func (x *RequestStrategyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStrategyPayload.ProtoReflect.Descriptor instead.
func (*RequestStrategyPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *RequestStrategyPayload) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type RequestReviewPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestReviewPayload) Reset() {
	*x = RequestReviewPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestReviewPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReviewPayload) ProtoMessage() {}

func (x *RequestReviewPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReviewPayload.ProtoReflect.Descriptor instead.
func (*RequestReviewPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *RequestReviewPayload) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type AvailableSpacesPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaces        []*SpaceInfo           `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableSpacesPayload) Reset() {
	*x = AvailableSpacesPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableSpacesPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableSpacesPayload) ProtoMessage() {}

func (x *AvailableSpacesPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableSpacesPayload.ProtoReflect.Descriptor instead.
func (*AvailableSpacesPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *AvailableSpacesPayload) GetSpaces() []*SpaceInfo {
	if x != nil {
		return x.Spaces
	}
	return nil
}

// --- Inbound Payloads (Client -> Server) ---
type SubmitPromptPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SpaceId       string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPromptPayload) Reset() {
	*x = SubmitPromptPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPromptPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPromptPayload) ProtoMessage() {}

func (x *SubmitPromptPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPromptPayload.ProtoReflect.Descriptor instead.
func (*SubmitPromptPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitPromptPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SubmitPromptPayload) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type SelectStrategyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    DelegationStrategy     `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3,enum=thinkspace.api.v1.DelegationStrategy" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectStrategyPayload) Reset() {
	*x = SelectStrategyPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectStrategyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectStrategyPayload) ProtoMessage() {}

func (x *SelectStrategyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectStrategyPayload.ProtoReflect.Descriptor instead.
func (*SelectStrategyPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *SelectStrategyPayload) GetStrategyId() DelegationStrategy {
	if x != nil {
		return x.StrategyId
	}
	return DelegationStrategy_DELEGATION_STRATEGY_UNSPECIFIED
}

type ReviewDecisionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewDecisionPayload) Reset() {
	*x = ReviewDecisionPayload{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewDecisionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewDecisionPayload) ProtoMessage() {}

func (x *ReviewDecisionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewDecisionPayload.ProtoReflect.Descriptor instead.
func (*ReviewDecisionPayload) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *ReviewDecisionPayload) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *ReviewDecisionPayload) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// --- The Master Envelope ---
type WSEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WSEvent_ChatStream
	//	*WSEvent_LogMessage
	//	*WSEvent_DelegationStart
	//	*WSEvent_DelegationComplete
	//	*WSEvent_AgentStart
	//	*WSEvent_AgentStream
	//	*WSEvent_AgentComplete
	//	*WSEvent_RequestStrategy
	//	*WSEvent_RequestReview
	//	*WSEvent_AvailableSpaces
	//	*WSEvent_SubmitPrompt
	//	*WSEvent_SelectStrategy
	//	*WSEvent_ReviewDecision
	Payload       isWSEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSEvent) Reset() {
	*x = WSEvent{}
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSEvent) ProtoMessage() {}

func (x *WSEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_thinkspace_api_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSEvent.ProtoReflect.Descriptor instead.
func (*WSEvent) Descriptor() ([]byte, []int) {
	return file_src_thinkspace_api_v1_events_proto_rawDescGZIP(), []int{14}
}

func (x *WSEvent) GetPayload() isWSEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WSEvent) GetChatStream() *ChatStreamPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_ChatStream); ok {
			return x.ChatStream
		}
	}
	return nil
}

func (x *WSEvent) GetLogMessage() *LogMessagePayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_LogMessage); ok {
			return x.LogMessage
		}
	}
	return nil
}

func (x *WSEvent) GetDelegationStart() *DelegationStartPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_DelegationStart); ok {
			return x.DelegationStart
		}
	}
	return nil
}

func (x *WSEvent) GetDelegationComplete() *DelegationCompletePayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_DelegationComplete); ok {
			return x.DelegationComplete
		}
	}
	return nil
}

func (x *WSEvent) GetAgentStart() *AgentStartPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_AgentStart); ok {
			return x.AgentStart
		}
	}
	return nil
}

func (x *WSEvent) GetAgentStream() *AgentStreamPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_AgentStream); ok {
			return x.AgentStream
		}
	}
	return nil
}

func (x *WSEvent) GetAgentComplete() *AgentCompletePayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_AgentComplete); ok {
			return x.AgentComplete
		}
	}
	return nil
}

func (x *WSEvent) GetRequestStrategy() *RequestStrategyPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_RequestStrategy); ok {
			return x.RequestStrategy
		}
	}
	return nil
}

func (x *WSEvent) GetRequestReview() *RequestReviewPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_RequestReview); ok {
			return x.RequestReview
		}
	}
	return nil
}

func (x *WSEvent) GetAvailableSpaces() *AvailableSpacesPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_AvailableSpaces); ok {
			return x.AvailableSpaces
		}
	}
	return nil
}

func (x *WSEvent) GetSubmitPrompt() *SubmitPromptPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_SubmitPrompt); ok {
			return x.SubmitPrompt
		}
	}
	return nil
}

func (x *WSEvent) GetSelectStrategy() *SelectStrategyPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_SelectStrategy); ok {
			return x.SelectStrategy
		}
	}
	return nil
}

func (x *WSEvent) GetReviewDecision() *ReviewDecisionPayload {
	if x != nil {
		if x, ok := x.Payload.(*WSEvent_ReviewDecision); ok {
			return x.ReviewDecision
		}
	}
	return nil
}

type isWSEvent_Payload interface {
	isWSEvent_Payload()
}

type WSEvent_ChatStream struct {
	// Outbound
	ChatStream *ChatStreamPayload `protobuf:"bytes,1,opt,name=chat_stream,json=chatStream,proto3,oneof"`
}

type WSEvent_LogMessage struct {
	LogMessage *LogMessagePayload `protobuf:"bytes,2,opt,name=log_message,json=logMessage,proto3,oneof"`
}

type WSEvent_DelegationStart struct {
	DelegationStart *DelegationStartPayload `protobuf:"bytes,3,opt,name=delegation_start,json=delegationStart,proto3,oneof"`
}

type WSEvent_DelegationComplete struct {
	DelegationComplete *DelegationCompletePayload `protobuf:"bytes,4,opt,name=delegation_complete,json=delegationComplete,proto3,oneof"`
}

type WSEvent_AgentStart struct {
	AgentStart *AgentStartPayload `protobuf:"bytes,5,opt,name=agent_start,json=agentStart,proto3,oneof"`
}

type WSEvent_AgentStream struct {
	AgentStream *AgentStreamPayload `protobuf:"bytes,6,opt,name=agent_stream,json=agentStream,proto3,oneof"`
}

type WSEvent_AgentComplete struct {
	AgentComplete *AgentCompletePayload `protobuf:"bytes,7,opt,name=agent_complete,json=agentComplete,proto3,oneof"`
}

type WSEvent_RequestStrategy struct {
	RequestStrategy *RequestStrategyPayload `protobuf:"bytes,8,opt,name=request_strategy,json=requestStrategy,proto3,oneof"`
}

type WSEvent_RequestReview struct {
	RequestReview *RequestReviewPayload `protobuf:"bytes,9,opt,name=request_review,json=requestReview,proto3,oneof"`
}

type WSEvent_AvailableSpaces struct {
	AvailableSpaces *AvailableSpacesPayload `protobuf:"bytes,10,opt,name=available_spaces,json=availableSpaces,proto3,oneof"`
}

type WSEvent_SubmitPrompt struct {
	// Inbound
	SubmitPrompt *SubmitPromptPayload `protobuf:"bytes,11,opt,name=submit_prompt,json=submitPrompt,proto3,oneof"`
}

type WSEvent_SelectStrategy struct {
	SelectStrategy *SelectStrategyPayload `protobuf:"bytes,12,opt,name=select_strategy,json=selectStrategy,proto3,oneof"`
}

type WSEvent_ReviewDecision struct {
	ReviewDecision *ReviewDecisionPayload `protobuf:"bytes,13,opt,name=review_decision,json=reviewDecision,proto3,oneof"`
}

func (*WSEvent_ChatStream) isWSEvent_Payload() {}

func (*WSEvent_LogMessage) isWSEvent_Payload() {}

func (*WSEvent_DelegationStart) isWSEvent_Payload() {}

func (*WSEvent_DelegationComplete) isWSEvent_Payload() {}

func (*WSEvent_AgentStart) isWSEvent_Payload() {}

func (*WSEvent_AgentStream) isWSEvent_Payload() {}

func (*WSEvent_AgentComplete) isWSEvent_Payload() {}

func (*WSEvent_RequestStrategy) isWSEvent_Payload() {}

func (*WSEvent_RequestReview) isWSEvent_Payload() {}

func (*WSEvent_AvailableSpaces) isWSEvent_Payload() {}

func (*WSEvent_SubmitPrompt) isWSEvent_Payload() {}

func (*WSEvent_SelectStrategy) isWSEvent_Payload() {}

func (*WSEvent_ReviewDecision) isWSEvent_Payload() {}

var File_src_thinkspace_api_v1_events_proto protoreflect.FileDescriptor

const file_src_thinkspace_api_v1_events_proto_rawDesc = "" +
	"\n" +
	"\"src/thinkspace/api/v1/events.proto\x12\x11thinkspace.api.v1\"/\n" +
	"\tSpaceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"'\n" +
	"\x11ChatStreamPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"C\n" +
	"\x11LogMessagePayload\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x16DelegationStartPayload\x12\x1f\n" +
	"\vagent_count\x18\x01 \x01(\x05R\n" +
	"agentCount\x12\"\n" +
	"\finstructions\x18\x02 \x01(\tR\finstructions\"5\n" +
	"\x19DelegationCompletePayload\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"R\n" +
	"\x11AgentStartPayload\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x05R\aagentId\x12\"\n" +
	"\finstructions\x18\x02 \x01(\tR\finstructions\"C\n" +
	"\x12AgentStreamPayload\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x05R\aagentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"e\n" +
	"\x14AgentCompletePayload\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x05R\aagentId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\"0\n" +
	"\x16RequestStrategyPayload\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\".\n" +
	"\x14RequestReviewPayload\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\"N\n" +
	"\x16AvailableSpacesPayload\x124\n" +
	"\x06spaces\x18\x01 \x03(\v2\x1c.thinkspace.api.v1.SpaceInfoR\x06spaces\"D\n" +
	"\x13SubmitPromptPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\"_\n" +
	"\x15SelectStrategyPayload\x12F\n" +
	"\vstrategy_id\x18\x01 \x01(\x0e2%.thinkspace.api.v1.DelegationStrategyR\n" +
	"strategyId\"K\n" +
	"\x15ReviewDecisionPayload\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"\xc1\b\n" +
	"\aWSEvent\x12G\n" +
	"\vchat_stream\x18\x01 \x01(\v2$.thinkspace.api.v1.ChatStreamPayloadH\x00R\n" +
	"chatStream\x12G\n" +
	"\vlog_message\x18\x02 \x01(\v2$.thinkspace.api.v1.LogMessagePayloadH\x00R\n" +
	"logMessage\x12V\n" +
	"\x10delegation_start\x18\x03 \x01(\v2).thinkspace.api.v1.DelegationStartPayloadH\x00R\x0fdelegationStart\x12_\n" +
	"\x13delegation_complete\x18\x04 \x01(\v2,.thinkspace.api.v1.DelegationCompletePayloadH\x00R\x12delegationComplete\x12G\n" +
	"\vagent_start\x18\x05 \x01(\v2$.thinkspace.api.v1.AgentStartPayloadH\x00R\n" +
	"agentStart\x12J\n" +
	"\fagent_stream\x18\x06 \x01(\v2%.thinkspace.api.v1.AgentStreamPayloadH\x00R\vagentStream\x12P\n" +
	"\x0eagent_complete\x18\a \x01(\v2'.thinkspace.api.v1.AgentCompletePayloadH\x00R\ragentComplete\x12V\n" +
	"\x10request_strategy\x18\b \x01(\v2).thinkspace.api.v1.RequestStrategyPayloadH\x00R\x0frequestStrategy\x12P\n" +
	"\x0erequest_review\x18\t \x01(\v2'.thinkspace.api.v1.RequestReviewPayloadH\x00R\rrequestReview\x12V\n" +
	"\x10available_spaces\x18\n" +
	" \x01(\v2).thinkspace.api.v1.AvailableSpacesPayloadH\x00R\x0favailableSpaces\x12M\n" +
	"\rsubmit_prompt\x18\v \x01(\v2&.thinkspace.api.v1.SubmitPromptPayloadH\x00R\fsubmitPrompt\x12S\n" +
	"\x0fselect_strategy\x18\f \x01(\v2(.thinkspace.api.v1.SelectStrategyPayloadH\x00R\x0eselectStrategy\x12S\n" +
	"\x0freview_decision\x18\r \x01(\v2(.thinkspace.api.v1.ReviewDecisionPayloadH\x00R\x0ereviewDecisionB\t\n" +
	"\apayload*\xb7\x01\n" +
	"\x12DelegationStrategy\x12#\n" +
	"\x1fDELEGATION_STRATEGY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DELEGATION_STRATEGY_SKIP\x10\x01\x12\x1e\n" +
	"\x1aDELEGATION_STRATEGY_MANUAL\x10\x02\x12\x1e\n" +
	"\x1aDELEGATION_STRATEGY_REVIEW\x10\x03\x12\x1e\n" +
	"\x1aDELEGATION_STRATEGY_REFINE\x10\x04B4Z2github.com/tinywideclouds/thinkspace/api/v1;api_v1b\x06proto3"

var (
	file_src_thinkspace_api_v1_events_proto_rawDescOnce sync.Once
	file_src_thinkspace_api_v1_events_proto_rawDescData []byte
)

func file_src_thinkspace_api_v1_events_proto_rawDescGZIP() []byte {
	file_src_thinkspace_api_v1_events_proto_rawDescOnce.Do(func() {
		file_src_thinkspace_api_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_thinkspace_api_v1_events_proto_rawDesc), len(file_src_thinkspace_api_v1_events_proto_rawDesc)))
	})
	return file_src_thinkspace_api_v1_events_proto_rawDescData
}

var file_src_thinkspace_api_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_thinkspace_api_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_src_thinkspace_api_v1_events_proto_goTypes = []any{
	(DelegationStrategy)(0),           // 0: thinkspace.api.v1.DelegationStrategy
	(*SpaceInfo)(nil),                 // 1: thinkspace.api.v1.SpaceInfo
	(*ChatStreamPayload)(nil),         // 2: thinkspace.api.v1.ChatStreamPayload
	(*LogMessagePayload)(nil),         // 3: thinkspace.api.v1.LogMessagePayload
	(*DelegationStartPayload)(nil),    // 4: thinkspace.api.v1.DelegationStartPayload
	(*DelegationCompletePayload)(nil), // 5: thinkspace.api.v1.DelegationCompletePayload
	(*AgentStartPayload)(nil),         // 6: thinkspace.api.v1.AgentStartPayload
	(*AgentStreamPayload)(nil),        // 7: thinkspace.api.v1.AgentStreamPayload
	(*AgentCompletePayload)(nil),      // 8: thinkspace.api.v1.AgentCompletePayload
	(*RequestStrategyPayload)(nil),    // 9: thinkspace.api.v1.RequestStrategyPayload
	(*RequestReviewPayload)(nil),      // 10: thinkspace.api.v1.RequestReviewPayload
	(*AvailableSpacesPayload)(nil),    // 11: thinkspace.api.v1.AvailableSpacesPayload
	(*SubmitPromptPayload)(nil),       // 12: thinkspace.api.v1.SubmitPromptPayload
	(*SelectStrategyPayload)(nil),     // 13: thinkspace.api.v1.SelectStrategyPayload
	(*ReviewDecisionPayload)(nil),     // 14: thinkspace.api.v1.ReviewDecisionPayload
	(*WSEvent)(nil),                   // 15: thinkspace.api.v1.WSEvent
}
var file_src_thinkspace_api_v1_events_proto_depIdxs = []int32{
	1,  // 0: thinkspace.api.v1.AvailableSpacesPayload.spaces:type_name -> thinkspace.api.v1.SpaceInfo
	0,  // 1: thinkspace.api.v1.SelectStrategyPayload.strategy_id:type_name -> thinkspace.api.v1.DelegationStrategy
	2,  // 2: thinkspace.api.v1.WSEvent.chat_stream:type_name -> thinkspace.api.v1.ChatStreamPayload
	3,  // 3: thinkspace.api.v1.WSEvent.log_message:type_name -> thinkspace.api.v1.LogMessagePayload
	4,  // 4: thinkspace.api.v1.WSEvent.delegation_start:type_name -> thinkspace.api.v1.DelegationStartPayload
	5,  // 5: thinkspace.api.v1.WSEvent.delegation_complete:type_name -> thinkspace.api.v1.DelegationCompletePayload
	6,  // 6: thinkspace.api.v1.WSEvent.agent_start:type_name -> thinkspace.api.v1.AgentStartPayload
	7,  // 7: thinkspace.api.v1.WSEvent.agent_stream:type_name -> thinkspace.api.v1.AgentStreamPayload
	8,  // 8: thinkspace.api.v1.WSEvent.agent_complete:type_name -> thinkspace.api.v1.AgentCompletePayload
	9,  // 9: thinkspace.api.v1.WSEvent.request_strategy:type_name -> thinkspace.api.v1.RequestStrategyPayload
	10, // 10: thinkspace.api.v1.WSEvent.request_review:type_name -> thinkspace.api.v1.RequestReviewPayload
	11, // 11: thinkspace.api.v1.WSEvent.available_spaces:type_name -> thinkspace.api.v1.AvailableSpacesPayload
	12, // 12: thinkspace.api.v1.WSEvent.submit_prompt:type_name -> thinkspace.api.v1.SubmitPromptPayload
	13, // 13: thinkspace.api.v1.WSEvent.select_strategy:type_name -> thinkspace.api.v1.SelectStrategyPayload
	14, // 14: thinkspace.api.v1.WSEvent.review_decision:type_name -> thinkspace.api.v1.ReviewDecisionPayload
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_src_thinkspace_api_v1_events_proto_init() }
func file_src_thinkspace_api_v1_events_proto_init() {
	if File_src_thinkspace_api_v1_events_proto != nil {
		return
	}
	file_src_thinkspace_api_v1_events_proto_msgTypes[14].OneofWrappers = []any{
		(*WSEvent_ChatStream)(nil),
		(*WSEvent_LogMessage)(nil),
		(*WSEvent_DelegationStart)(nil),
		(*WSEvent_DelegationComplete)(nil),
		(*WSEvent_AgentStart)(nil),
		(*WSEvent_AgentStream)(nil),
		(*WSEvent_AgentComplete)(nil),
		(*WSEvent_RequestStrategy)(nil),
		(*WSEvent_RequestReview)(nil),
		(*WSEvent_AvailableSpaces)(nil),
		(*WSEvent_SubmitPrompt)(nil),
		(*WSEvent_SelectStrategy)(nil),
		(*WSEvent_ReviewDecision)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_thinkspace_api_v1_events_proto_rawDesc), len(file_src_thinkspace_api_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_thinkspace_api_v1_events_proto_goTypes,
		DependencyIndexes: file_src_thinkspace_api_v1_events_proto_depIdxs,
		EnumInfos:         file_src_thinkspace_api_v1_events_proto_enumTypes,
		MessageInfos:      file_src_thinkspace_api_v1_events_proto_msgTypes,
	}.Build()
	File_src_thinkspace_api_v1_events_proto = out.File
	file_src_thinkspace_api_v1_events_proto_goTypes = nil
	file_src_thinkspace_api_v1_events_proto_depIdxs = nil
}
